name: Create Release
on:
  push:
    # run only on tags
    tags:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/workflow-build.yaml
    secrets: inherit
  gh-release:
    name: Create a GitHub Release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
