name: Main

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/workflow-build.yaml
    secrets: inherit
